/**
 * Writes `src/types/version.ts`, exporting this package's `package.json` version as a Luau/TS
 * constant, so the Studio plugin (which has no filesystem access to package.json at runtime) can
 * display its own version. Run before any compile (`build`, `build:bridge`) so the constant can
 * never drift from package.json the way `plugin/ScreenshotPlugin.rbxm` silently did before.
 */
const fs = require("node:fs");
const path = require("node:path");

const packageJsonPath = path.join(__dirname, "..", "package.json");
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, "utf8"));
const version = packageJson.version;
if (typeof version !== "string" || version.length === 0) {
	throw new Error(`${packageJsonPath} is missing a valid "version" field`);
}

const outputPath = path.join(__dirname, "..", "src", "types", "version.ts");
const contents = `/** Generated by scripts/generate-version.js from package.json's "version" field - do not edit by hand. */\nexport const PACKAGE_VERSION = ${JSON.stringify(version)};\n`;
fs.writeFileSync(outputPath, contents, "utf8");
console.log(`Wrote ${outputPath} (PACKAGE_VERSION = ${JSON.stringify(version)})`);
